# The URL the site will be built for
base_url = "https://webodm.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

[extra]
# Put all your custom variables here
site_title = "WebODM - Drone Mapping Software"
site_description = "Free and Open Source Drone Mapping Software"
primary_color = "#6893d8"
